// React_App/src/App.js
import { useState } from "react";

function App() {
  const [messageInput, setMessageInput] = useState('');
  const [displayedMessage, setDisplayedMessage] = useState('Hello World');

  const handleClick = () => {
    setDisplayedMessage(messageInput);
  };

  return (
    <div>
    <label htmlFor="message">Message to Display: </label>
    <input 
    id="message"
    type="text"
    value={messageInput}
    onChange={(e) => setMessageInput(e.target.value)}
    />
    <button onClick={handleClick}>Display Message</button>
    <h2>{displayedMessage}</h2>
    </div>
  );
}

export default App;

// todo/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'todo';
  messageInput: string = '';
  displayedMessage: string = 'Hello World!';

  updateMessage() {
    this.displayedMessage = this.messageInput;
  }
}

<div>
  <label for="message">Message to Display: </label>
  <input id="message" [(ngModel)]="messageInput" type="text" />
  <button (click)="updateMessage()">Display Message</button>
  <h2>{{ displayedMessage }}</h2>
</div>
